robot_names:
  - 'barrett'
  - 'allegro'
  - 'shadowhand'

debug_object_names: null  # use part of the dataset, for debug only

batch_size: 2  # 1 batch_size â‰ˆ 4 GB GPU memory during training
num_workers: 4

object_pc_type: 'random'  # 'fixed', 'random', 'partial'
