defaults:
  - log.yaml
  - model.yaml
  - dataset: cmap_dataset.yaml
  - _self_

name: 'model_3robots_diffusion'

seed: 42
gpu:
  - 0
log_every_n_steps: 5
load_from_checkpoint: False

training:
  max_epochs: 200
  save_dir: '${output_dir}/state_dict'
  save_every_n_epoch: 5

  lr: 1e-4

  # ===== Loss settings =====
  dro_weight: 1.0
  rec_weight: 1.0
  diffusion_weight: 1.0

  kl_weight: 0.01
  diffusion_kl_weight: 0.01

  loss_se3: false
  loss_depth: false

model:
  use_diffusion: true
  diffusion_timesteps: 100

