defaults:
  - model.yaml
  - dataset: cmap_dataset.yaml
  - _self_

model:
  pretrain: null
  use_diffusion: true
  diffusion_timesteps: 100

dataset:
  batch_size: 20

split_batch_size: 5
gpu: 0

name: 'model_3robots_diffusion'

validate_epochs:
  - 150
  - 175
  - 200
use_decoder_ik: false
decoder_K: 256

validate:
  sample_K: 7
